version: '3.1'
services:
  ewm-main-server:
    image: ewm-main-server
    build: ewm-main-server/.
    container_name: ewm-main-server
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"
    depends_on:
      - ewm-stat-server
      - ewm-db
    environment:
      - MAIN_PORT=${MAIN_PORT}
      - MAIN_DB_PORT=5432
      - URL_DB=postgresql://ewm-db:5432/explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-stat-server:
    image: ewm-stat-server
    build: ewm-stat-server/stat_service/.
    container_name: ewm-stat-server
    ports:
      - "${STAT_PORT}:${STAT_PORT}"
    depends_on:
      - stats-db
    environment:
      - STAT_PORT=${STAT_PORT}
      - STAT_DB_PORT=5432
      - STAT_URL_DB=postgresql://stats-db:5432/explore-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "${STAT_DB_PORT}:5432"
    environment:
      - POSTGRES_DB=explore-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "${MAIN_DB_PORT}:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root