version: "3.1"

services:

  stats-server:
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    build: ewm-stat-service/stat_service/.
    environment:
      - STAT_PORT=${STAT_PORT}
      - STAT_DB_PORT=5432
      - STAT_DB_PATH=${STAT_DB_PATH}
      - STAT_DB_NAME=${STAT_DB_NAME}
      - STAT_DB_LOGIN=${STAT_DB_LOGIN}
      - STAT_DB_PASSWORD=${STAT_DB_PASSWORD}
    restart: on-failure

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    command: "-c logging_collector=on -c log_statement=all"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=${STAT_DB_NAME}
      - POSTGRES_USER=${STAT_DB_LOGIN}
      - POSTGRES_PASSWORD=${STAT_DB_PASSWORD}