CREATE TABLE IF NOT EXISTS ewm_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_NAME UNIQUE (username),
    CONSTRAINT UQ_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(50) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id),
    CONSTRAINT UQ_TITLE UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    participant_limit BIGINT NOT NULL,
    latitude FLOAT,
    longitude FLOAT,
    paid BOOLEAN NOT NULL,
    moderation BOOLEAN NOT NULL,
    state VARCHAR(15),
    created TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE,
    published TIMESTAMP WITHOUT TIME ZONE,
    initiator_id BIGINT REFERENCES ewm_users (id) NOT NULL,
    category_id BIGINT REFERENCES categories (id) NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event (
    compilation_id BIGINT REFERENCES compilations (id) NOT NULL,
    event_id BIGINT REFERENCES events (id) NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS participations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status VARCHAR(15),
    created TIMESTAMP WITHOUT TIME ZONE,
    requester_id BIGINT REFERENCES ewm_users (id) NOT NULL,
    event_id BIGINT REFERENCES events (id) NOT NULL,
    CONSTRAINT pk_participation PRIMARY KEY (id)
);